# Data Pre-Processing

## Importing the Libraries

In [1]:
import pandas as pd 
import numpy as np 
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

## Dataset

In [3]:
dataset = pd.read_excel("./Dataset/Folds5x2_pp.xlsx")

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [5]:
dataset.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [6]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [7]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Splitting the Dataset into train and test set

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Building the ANN

## Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

## Adding the input and first hidden layer

In [10]:
# Input layer neurons are automatically detected by TensorFlow when we enter the Matrix of Features (X), so we don't need to specify it.

ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) # First Hidden Layer

## Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) # Second Hidden Layer

## Adding the Output Layer

In [12]:
ann.add(tf.keras.layers.Dense(units = 1)) # or softmax(Have more than 2 categories) & sigmoid (Yes or No) are used for classfication but this is a regression problem, so we don't keep any activation function.

# Training the ANN

## Compiling the ANN

In [13]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])

## Training the ANN on the Training Set

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 982us/step - loss: 13848.6377 - accuracy: 0.0000e+00
Epoch 2/100
240/240 [==============================] - 0s 730us/step - loss: 388.9727 - accuracy: 0.0000e+00
Epoch 3/100
240/240 [==============================] - 0s 721us/step - loss: 368.5107 - accuracy: 0.0000e+00
Epoch 4/100
240/240 [==============================] - 0s 734us/step - loss: 261.8324 - accuracy: 0.0000e+00
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 216.2119 - accuracy: 0.0000e+00
Epoch 6/100
240/240 [==============================] - 0s 895us/step - loss: 183.1771 - accuracy: 0.0000e+00
Epoch 7/100
240/240 [==============================] - 0s 759us/step - loss: 157.6429 - accuracy: 0.0000e+00
Epoch 8/100
240/240 [==============================] - 0s 692us/step - loss: 137.3903 - accuracy: 0.0000e+00
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 121.2400 - accuracy: 0.0000e+00
Epoch 10/100
240/240 

## Predicting the result of Test set

In [15]:
y_pred = ann.predict(X_test)

np.set_printoptions(precision=2)
print("Predict | Actual")
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)[0:20])

Predict | Actual
[[431.05 431.23]
 [462.13 460.01]
 [465.64 461.14]
 [448.72 445.9 ]
 [459.94 451.29]
 [429.12 432.68]
 [471.51 477.5 ]
 [457.49 459.68]
 [475.06 477.5 ]
 [443.9  444.99]
 [442.06 444.37]
 [441.71 437.04]
 [446.36 442.34]
 [442.08 440.74]
 [437.89 436.55]
 [455.58 460.24]
 [447.78 448.66]
 [437.06 432.94]
 [451.12 452.82]
 [428.2  432.2 ]]
