# Importing the libraries

In [20]:
import tensorflow as tf 
import pandas as pd
import numpy as np

# Data Pre-Processing

## Loading the Dataset

In [21]:
dataset = pd.read_csv("../Dataset/winequality-red.csv", sep = ";")

In [22]:
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [23]:
dataset["quality"].unique()

array([5, 6, 7, 4, 8, 3])

In [24]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [25]:
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [26]:
y

array([5, 5, 5, ..., 6, 5, 6])

## Splitting the dataset into Training and Test Set

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

## Feature Scaling

In [29]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

# Building the ANN

In [30]:
ann = tf.keras.models.Sequential() # Initializing the ANN

ann.add(tf.keras.layers.Dense(units=8, activation='relu')) # First Hidden Layer
ann.add(tf.keras.layers.Dense(units=8, activation='relu')) # Second Hidden Layer

ann.add(tf.keras.layers.Dense(units = 10, activation = 'softmax'))

# Training the ANN

In [31]:
ann.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [32]:
ann.fit(X_train, y_train, epochs = 100)

Epoch 1/100
40/40 [==============================] - 0s 2ms/step - loss: 3.5726 - accuracy: 0.3628
Epoch 2/100
40/40 [==============================] - 0s 4ms/step - loss: 2.5449 - accuracy: 0.4222
Epoch 3/100
40/40 [==============================] - 0s 1ms/step - loss: 2.1638 - accuracy: 0.4402
Epoch 4/100
40/40 [==============================] - 0s 1ms/step - loss: 2.0728 - accuracy: 0.4261
Epoch 5/100
40/40 [==============================] - 0s 1ms/step - loss: 2.0108 - accuracy: 0.4261
Epoch 6/100
40/40 [==============================] - 0s 2ms/step - loss: 1.9571 - accuracy: 0.4261
Epoch 7/100
40/40 [==============================] - 0s 2ms/step - loss: 1.9106 - accuracy: 0.4261
Epoch 8/100
40/40 [==============================] - 0s 2ms/step - loss: 1.8662 - accuracy: 0.4261
Epoch 9/100
40/40 [==============================] - 0s 1ms/step - loss: 1.8262 - accuracy: 0.4261
Epoch 10/100
40/40 [==============================] - 0s 1ms/step - loss: 1.7890 - accuracy: 0.4261
Epoch 11/

# Evaluating Predictions and testing accuracy

In [33]:
test_loss, test_acc = ann.evaluate(X_test,  y_test, verbose=1) 

print('Test accuracy:', test_acc)

10/10 [==============================] - 0s 834us/step - loss: 1.1682 - accuracy: 0.5125
Test accuracy: 0.512499988079071


In [34]:
predictions = ann.predict(X_test)

In [35]:
predictions

array([[1.0727660e-02, 6.1974162e-03, 4.6111410e-03, ..., 1.7230010e-01,
        1.8673278e-02, 6.2541626e-03],
       [8.6461892e-03, 3.0785690e-03, 1.7279472e-03, ..., 1.3962480e-01,
        1.3133793e-02, 3.1336783e-03],
       [7.1405596e-03, 1.7463968e-03, 7.8763050e-04, ..., 1.1579761e-01,
        9.7587416e-03, 1.7896025e-03],
       ...,
       [9.8615400e-03, 4.6700244e-03, 3.0948138e-03, ..., 1.5874259e-01,
        1.6231718e-02, 4.7295135e-03],
       [1.8463266e-03, 5.8091620e-05, 7.9355768e-06, ..., 3.0638305e-02,
        1.4168784e-03, 6.1745457e-05],
       [5.1562479e-03, 7.1464526e-04, 2.3153226e-04, ..., 8.4152594e-02,
        6.0059396e-03, 7.3977816e-04]], dtype=float32)

In [36]:
y_pred = []

for i in range(0,len(predictions)):
    y_pred.append(np.argmax(predictions[i]))

In [37]:
y_pred[0:10]

[6, 6, 6, 6, 6, 5, 6, 5, 6, 5]

In [39]:
y_test[0:10]

array([6, 7, 6, 5, 6, 4, 6, 6, 6, 5])